proto/orijtech: define per point data
orijtech/cosmosloadtester pull request #21
Opened 2022-12-20 00:14 UTC by odeke-em

Updates the protobuf definitions to have per point data that can then be used by the user interface.

Updates #14
Updates #16

2022-12-20 01:05 UTC, kirbyquerby requested changes

2022-12-21 09:18 UTC, willpoint commented
@odeke-em @kirbyquerby how do we proceed on this, so I can update the frontend as well.

2022-12-22 11:27 UTC, odeke-em commented on proto/orijtech/cosmosloadtester/v1/loadtest_service.proto
> +  string at_str = 4;
Human friendly representation of when the value occured. Pretty useful for debugging. I've documented it.

2022-12-22 11:27 UTC, odeke-em commented on proto/orijtech/cosmosloadtester/v1/loadtest_service.proto
> +  repeated PerSecond per_sec = 6;
Done, thanks @kirbyquerby!

2022-12-22 11:28 UTC, odeke-em commented on proto/orijtech/cosmosloadtester/v1/loadtest_service.proto
> +  google.protobuf.Duration latency = 2;
Percentile can have both latency or size, I suppose we can use a oneof type for these but it is much simpler to have them both; when we have bytes_rankings, latency is unset, when we have latency_rankings, size is unset

2022-12-22 11:28 UTC, odeke-em commented on proto/orijtech/cosmosloadtester/v1/loadtest_service.proto
> +  int64 sec = 1;
It is!

2022-12-22 11:31 UTC, odeke-em commented on proto/orijtech/cosmosloadtester/v1/loadtest_service.proto
> +  int64 sec = 1;
No, it is an ordinal number for example sec=0, sec=10 and essentially the lower bound of time bucket.

2022-12-22 11:32 UTC, odeke-em commented on proto/orijtech/cosmosloadtester/v1/loadtest_service.proto
> +  double bytes = 3;
Done, thanks @kirbyquerby!

2022-12-22 11:33 UTC, odeke-em commented on proto/orijtech/cosmosloadtester/v1/loadtest_service.proto
> +  google.protobuf.Duration at = 1;
I've updated it to start_offset

2022-12-22 11:34 UTC, odeke-em commented
Thanks for the review @kirbyquerby! Updated with the AIP suggestions. @willpoint thanks for the ping! We are almost there, I've made some changes and regenerated the protobuf. Just another round of reviews!

2022-12-22 23:04 UTC, kirbyquerby approved these changes
Approving because of timeline constraints.

2022-12-22 23:04 UTC, kirbyquerby commented on proto/orijtech/cosmosloadtester/v1/loadtest_service.proto
> +  int64 sec = 1;
So this is the duration (floored to the nearest second) relative to the start of the load test.

2022-12-22 23:16 UTC, kirbyquerby commented on proto/orijtech/cosmosloadtester/v1/loadtest_service.proto
> +  repeated PerSecond per_sec = 6;
@odeke-em in chat, you mentioned:
> about the slice: we might have scenarios in which there is more than 1 connection so safe to return it as a slice. For starters let’s let it display stats per transactor. Once the app is being used we shall have breathing space to display an aggregation

This proto definition only returns aggregate values, while the custom tm-load-test returns a `[]*ProcessedStats`, with an entry for each transactor:

https://github.com/orijtech/tm-load-test/blob/d37154798c88c311e880eb23ec799d09e04cb44b/pkg/loadtest/loadtest.go#L15

Should the proto be changed or should the implementation aggregate the stats?

2022-12-23 07:21 UTC, willpoint approved these changes
LGTM

2022-12-23 21:23 UTC, kirbyquerby commented
Merging to unblock UI.

2022-12-23 21:23 UTC, merged